name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  MSRV: 1.69.0

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Check format
        run: cargo fmt --all --check

      - name: Check clippy
        run: cargo clippy

      - name: Unit tests
        run: cargo test

  check_msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: '${{ env.MSRV }}'
          components: clippy, rustfmt

      - name: Check clippy
        run: cargo clippy

      - name: Unit tests
        run: cargo test
